### ISSUE TITLE
Cannot run `npm run build` on Linux

### ISSUE THREAD

**Issue by me97esn** [KTH/style#2]
I'm getting the following error:

style git:(main) npm run build
> build
> lerna run build

lerna notice cli v6.6.1
lerna info versioning independent

 >  Lerna (powered by Nx)   Cannot find module '@nrwl/nx-linux-x64-gnu'

   Require stack:
   - /home/emil/workspace/kth/style/node_modules/nx/src/native/index.js
   - /home/emil/workspace/kth/style/node_modules/nx/src/hasher/native-file-hasher.js
   - /home/emil/workspace/kth/style/node_modules/nx/src/hasher/file-hasher.js
   - /home/emil/workspace/kth/style/node_modules/nx/src/project-graph/build-project-graph.js
   - /home/emil/workspace/kth/style/node_modules/nx/src/project-graph/project-graph.js
   - /home/emil/workspace/kth/style/node_modules/nx/src/project-graph/file-utils.js
   - /home/emil/workspace/kth/style/node_modules/nx/src/devkit-exports.js
   - /home/emil/workspace/kth/style/node_modules/@nrwl/devkit/index.js
   - /home/emil/workspace/kth/style/node_modules/lerna/dist/cli.js

**Comment by exacs** [comment]
Thanks for your report! Can you give us a bit more information?

- Commands you have run before running `npm run build`: `npm install` maybe?
- What is the output when you run `node -v` and `npm -v`?
- Which directory do you run `npm run build` command?

**Comment by exacs** [comment]
Closing this issue. I've noticed now that it was opened in July
